# 球队名称中英文对照表

TEAM_NAMES = {
    # 英超
    "Arsenal": "阿森纳",
    "Aston Villa": "维拉",
    "Bournemouth": "伯恩茅斯",
    "Brentford": "布伦特福德",
    "Brighton": "布莱顿",
    "Burnley": "伯恩利",
    "Chelsea": "切尔西",
    "Crystal Palace": "水晶宫",
    "Everton": "埃弗顿",
    "Fulham": "富勒姆",
    "Liverpool": "利物浦",
    "Leeds": "利兹",
    "Leicester": "莱斯特城",
    "Man City": "曼城",
    "Manchester City": "曼城",
    "Man United": "曼联",
    "Manchester United": "曼联",
    "Newcastle": "纽卡斯尔",
    "Nott'm Forest": "诺丁汉森林",
    "Nottingham Forest": "诺丁汉森林",
    "Southampton": "南安普顿",
    "Tottenham": "热刺",
    "West Ham": "西汉姆",
    "Wolves": "狼队",
    "Wolverhampton": "狼队",
    "Wolverhampton Wanderers": "狼队",
    "Sunderland": "桑德兰",
    "Ipswich": "伊普斯维奇",
    "Luton": "卢顿",
    "Millwall": "米尔沃尔",
    "Coventry": "考文垂",
    "Middlesbrough": "米堡",
    "Bristol City": "布里斯托城",
    "Cardiff": "卡迪夫城",
    "Hull": "赫尔城",
    "Stoke": "斯托克城",
    "Swansea": "斯旺西",
    "West Brom": "西布朗",
    "Sheffield Utd": "谢菲联",
    "Sheffield United": "谢菲联",
    "Watford": "沃特福德",
    "Norwich": "诺维奇",
    "Preston": "普雷斯顿",
    "Blackburn": "布莱克本",
    "Derby": "德比郡",
    "Reading": "雷丁",
    "Birmingham": "伯明翰",

    # 西甲
    "Real Madrid": "皇马",
    "Barcelona": "巴萨",
    "Atletico Madrid": "马竞",
    "Atletico": "马竞",
    "Sevilla": "塞维利亚",
    "Villarreal": "比利亚雷亚尔",
    "Real Betis": "贝蒂斯",
    "Betis": "贝蒂斯",
    "Real Sociedad": "皇社",
    "Athletic Bilbao": "毕巴",
    "Athletic": "毕巴",
    "Valencia": "瓦伦西亚",
    "Girona": "赫罗纳",
    "Getafe": "赫塔菲",
    "Osasuna": "奥萨苏纳",
    "Celta Vigo": "塞尔塔",
    "Mallorca": "马洛卡",
    "Las Palmas": "拉斯帕尔马斯",
    "Rayo Vallecano": "巴列卡诺",
    "Espanyol": "西班牙人",
    "Alaves": "阿拉维斯",
    "Valladolid": "巴拉多利德",
    "Cadiz": "加的斯",
    "Granada": "格拉纳达",
    "Almeria": "阿尔梅里亚",
    "Levante": "莱万特",
    "Leganes": "莱加内斯",
    "Eibar": "埃瓦尔",

    # 意甲
    "Inter Milan": "国米",
    "Inter": "国米",
    "AC Milan": "AC米兰",
    "Milan": "AC米兰",
    "Juventus": "尤文",
    "Napoli": "那不勒斯",
    "Roma": "罗马",
    "Lazio": "拉齐奥",
    "Fiorentina": "佛罗伦萨",
    "Atalanta": "亚特兰大",
    "Torino": "都灵",
    "Sassuolo": "萨索洛",
    "Empoli": "恩波利",
    "Bologna": "博洛尼亚",
    "Udinese": "乌迪内斯",
    "Sampdoria": "桑普多利亚",
    "Genoa": "热那亚",
    "Lecce": "莱切",
    "Verona": "维罗纳",
    "Hellas Verona": "维罗纳",
    "Monza": "蒙扎",
    "Frosinone": "弗罗西诺内",
    "Salernitana": "萨勒尼塔纳",
    "Cremonese": "克雷莫内塞",
    "Spal": "SPAL",
    "Parma": "帕尔马",
    "Cagliari": "卡利亚里",
    "Spezia": "斯佩齐亚",
    "Benevento": "贝内文托",
    "Brescia": "布雷西亚",

    # 德甲
    "Bayern Munich": "拜仁",
    "Bayern": "拜仁",
    "Borussia Dortmund": "多特",
    "Dortmund": "多特",
    "RB Leipzig": "莱比锡",
    "Leipzig": "莱比锡",
    "Bayer Leverkusen": "勒沃库森",
    "Leverkusen": "勒沃库森",
    "Eintracht Frankfurt": "法兰克福",
    "Frankfurt": "法兰克福",
    "Wolfsburg": "沃尔夫斯堡",
    "Wolfsburger": "沃尔夫斯堡",
    "Borussia Monchengladbach": "门兴",
    "Monchengladbach": "门兴",
    "Gladbach": "门兴",
    "Union Berlin": "柏林联合",
    "Freiburg": "弗赖堡",
    "SC Freiburg": "弗赖堡",
    "Hoffenheim": "霍芬海姆",
    "1899 Hoffenheim": "霍芬海姆",
    "Stuttgart": "斯图加特",
    "VFB Stuttgart": "斯图加特",
    "Mainz": "美因茨",
    "Mainz 05": "美因茨",
    "Koln": "科隆",
    "FC Cologne": "科隆",
    "Cologne": "科隆",
    "Hertha Berlin": "柏林赫塔",
    "Hertha": "柏林赫塔",
    "Augsburg": "奥格斯堡",
    "Arminia Bielefeld": "比勒菲尔德",
    "Bielefeld": "比勒菲尔德",
    "Schalke": "沙尔克",
    "Schalke 04": "沙尔克04",
    "Bochum": "波鸿",
    "VFL Bochum": "波鸿",
    "Darmstadt": "达姆施塔特",
    "Heidenheim": "海登海姆",
    "SV Darmstadt 98": "达姆施塔特",
    "FC Heidenheim": "海登海姆",
    "Paderborn": "帕德博恩",
    "SC Paderborn": "帕德博恩",
    "Nurnberg": "纽伦堡",
    "Nuremberg": "纽伦堡",
    "Greuther Furth": "菲尔特",
    "Werder Bremen": "不莱梅",
    "Bremen": "不莱梅",
    "St Pauli": "圣保利",

    # 法甲
    "PSG": "巴黎",
    "Paris Saint-Germain": "巴黎",
    "Paris": "巴黎",
    "Marseille": "马赛",
    "Olympique Marseille": "马赛",
    "Lyon": "里昂",
    "Olympique Lyon": "里昂",
    "Monaco": "摩纳哥",
    "AS Monaco": "摩纳哥",
    "Lille": "里尔",
    "Nice": "尼斯",
    "Rennes": "雷恩",
    "St Etienne": "圣埃蒂安",
    "Saint-Etienne": "圣埃蒂安",
    "Strasbourg": "斯特拉斯堡",
    "RC Strasbourg": "斯特拉斯堡",
    "Montpellier": "蒙彼利埃",
    "MHSC": "蒙彼利埃",
    "Bordeaux": "波尔多",
    "Girondins Bordeaux": "波尔多",
    "Nantes": "南特",
    "FC Nantes": "南特",
    "Brest": "布雷斯特",
    "Stade Brestois": "布雷斯特",
    "Lens": "朗斯",
    "RC Lens": "朗斯",
    "Toulouse": "图卢兹",
    "FC Toulouse": "图卢兹",
    "Metz": "梅斯",
    "FC Metz": "梅斯",
    "Reims": "兰斯",
    "Stade de Reims": "兰斯",
    "Angers": "昂热",
    "SCO Angers": "昂热",
    "Clermont": "克莱蒙",
    "Clermont Foot": "克莱蒙",
    "Auxerre": "欧塞尔",
    "AJ Auxerre": "欧塞尔",
    "Lorient": "洛里昂",
    "FC Lorient": "洛里昂",
    "Troyes": "特鲁瓦",
    "ESTAC Troyes": "特鲁瓦",
    "Ajaccio": "阿雅克肖",
    "AC Ajaccio": "阿雅克肖",
    "Nimes": "尼姆",
    "Nimes Olympique": "尼姆",
    "Dijon": "第戎",
    "Dijon FCO": "第戎",
    "Le Havre": "勒阿弗尔",
}


def get_team_name(en_name):
    """根据英文名返回中文名"""
    if en_name in TEAM_NAMES:
        return TEAM_NAMES[en_name]
    # 模糊匹配
    for en, cn in TEAM_NAMES.items():
        if en.lower() in en_name.lower() or en_name.lower() in en.lower():
            return cn
    return en_name
